server:
  port: 10005
zuul:
  routes:
    service-provider: /provicer/** #service-provider服务的路由
    service-consumer: /consumer/** #service-consumer服务的路由
  prefix: /api #访问前缀
eureka:
  client:
    service-url: # 指定注册中心EurekaServer地址
      defaultZone: http://127.0.0.1:10001/eureka