server:
  port: 8081 #端口号
  servlet:
    context-path: /ghxt #项目访问上下文
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hchvhg
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.6
    port: 6379
mybatis:
  mapper-locations: classpath:mybatis/*.xml #扫描mybatis目录下所有xml文件作为mapper